[CmdletBinding()]
param(
    [string]$ReleaseVersion = '0.0.3',
    [switch]$SkipTests,
    [bool]$CreateZip = $true,
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

function Write-Step([string]$Message) {
    Write-Host "[release] $Message"
}

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$releaseName = "MDir_v$ReleaseVersion"
$targetDir = Join-Path $repoRoot 'target'
$releaseRoot = Join-Path $repoRoot "release\$releaseName"
$appDir = Join-Path $releaseRoot 'app'
$libDir = Join-Path $appDir 'lib'
$binDir = Join-Path $releaseRoot 'bin'
$zipPath = Join-Path $repoRoot "${releaseName}_release.zip"
$buildArgs = @('-Prelease', 'clean', 'package')
if ($SkipTests) { $buildArgs += '-DskipTests' }

$launcherBat = @'
@echo off
REM MDir Image ^& Video Organizer - Windows Launcher
setlocal
set "SCRIPT_DIR=%~dp0"
set "APP_DIR=%SCRIPT_DIR%..\app"
if not exist "%APP_DIR%\mdir.jar" (
    echo Error: mdir.jar not found at "%APP_DIR%\mdir.jar"
    pause
    exit /b 1
)
echo Launching MDir Image ^& Video Organizer...
java --enable-native-access=ALL-UNNAMED -cp "%APP_DIR%\mdir.jar;%APP_DIR%\lib\*" com.girbola.Launcher
if errorlevel 1 (
    echo.
    echo Error: Failed to start the application.
    echo Check console output above for details.
    pause
    exit /b 1
)
endlocal
'@

$launcherSh = @'
#!/bin/bash
# MDir Image & Video Organizer - macOS/Linux Launcher
set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APP_DIR="$(cd "$SCRIPT_DIR/../app" && pwd)"
if [ ! -f "$APP_DIR/mdir.jar" ]; then
  echo "Error: mdir.jar not found at $APP_DIR/mdir.jar"
  exit 1
fi
echo "Launching MDir Image & Video Organizer..."
java --enable-native-access=ALL-UNNAMED -cp "$APP_DIR/mdir.jar:$APP_DIR/lib/*" com.girbola.Launcher
'@

$releaseReadme = @"
# MDir v$ReleaseVersion Release

This folder was generated by `scripts/build-release.ps1`.

## Run

- Windows: `bin\run.bat`
- macOS/Linux: `chmod +x bin/run.sh && ./bin/run.sh`

## Requirements

- Java 24+
- Extract the ZIP before running
"@

if ($DryRun) {
    Write-Step "Dry run enabled"
    Write-Step "Repo root: $repoRoot"
    Write-Step "Release folder: $releaseRoot"
    Write-Step "Would run: mvn $($buildArgs -join ' ')"
    return
}

foreach ($cmd in @('mvn', 'java')) {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
        throw "Required command not found: $cmd"
    }
}

Write-Step "Building project with Maven (release profile)"
& mvn @buildArgs

$jar = Get-ChildItem $targetDir -Filter '*.jar' |
    Where-Object { $_.Name -notlike 'original-*' -and $_.Name -notlike '*sources*' -and $_.Name -notlike '*javadoc*' } |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

if (-not $jar) {
    throw "No application JAR found in $targetDir"
}

# Runtime deps are already in target/release-lib (copied by the release Maven profile)
$releaseLibSrc = Join-Path $targetDir 'release-lib'
if (-not (Test-Path $releaseLibSrc)) {
    throw "target/release-lib not found - make sure the 'release' Maven profile ran correctly."
}

Write-Step "Preparing release folder: $releaseRoot"
Remove-Item $releaseRoot -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force -Path $libDir, $binDir | Out-Null

Copy-Item $jar.FullName (Join-Path $appDir 'mdir.jar')
Copy-Item "$releaseLibSrc\*" $libDir -Recurse
Set-Content -Path (Join-Path $binDir 'run.bat') -Value $launcherBat -Encoding ASCII
Set-Content -Path (Join-Path $binDir 'run.sh') -Value $launcherSh -Encoding ASCII
Set-Content -Path (Join-Path $releaseRoot 'README.md') -Value $releaseReadme -Encoding UTF8


Write-Step "Creating ZIP archive"
if ($CreateZip) {
    if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
    $releaseParent = Split-Path $releaseRoot -Parent
    $archiveCreated = $false

    if (Get-Command tar -ErrorAction SilentlyContinue) {
        try {
            & tar -a -c -f $zipPath -C $releaseParent $releaseName | Out-Null
            $archiveCreated = $true
        } catch {
            Write-Warning "tar archive creation failed: $($_.Exception.Message)"
        }
    }

    if (-not $archiveCreated) {
        try {
            Compress-Archive -Path (Join-Path $releaseRoot '*') -DestinationPath $zipPath -CompressionLevel Optimal -ErrorAction Stop
            $archiveCreated = $true
        } catch {
            Write-Warning "ZIP creation failed: $($_.Exception.Message)"
        }
    }

    if ($archiveCreated) {
        Write-Step "ZIP created: $zipPath"
    } else {
        Write-Step "Skipping ZIP output; release folder is still ready"
    }
}

Write-Step "Release folder ready: $releaseRoot"



