#!/usr/bin/env bash
set -euo pipefail

RELEASE_VERSION="${RELEASE_VERSION:-0.0.3}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RELEASE_NAME="MDir_v${RELEASE_VERSION}"
TARGET_DIR="$REPO_ROOT/target"
RELEASE_ROOT="$REPO_ROOT/release/$RELEASE_NAME"
APP_DIR="$RELEASE_ROOT/app"
LIB_DIR="$APP_DIR/lib"
BIN_DIR="$RELEASE_ROOT/bin"
ZIP_PATH="$REPO_ROOT/${RELEASE_NAME}_release.zip"

log() { printf '[release] %s\n' "$*"; }

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "Required command not found: $1" >&2; exit 1; }
}

need_cmd mvn
need_cmd java

log "Building project with Maven (release profile)"
mvn -Prelease clean package -DskipTests

JAR_FILE="$(find "$TARGET_DIR" -maxdepth 1 -name '*.jar' ! -name 'original-*' ! -name '*sources*' ! -name '*javadoc*' | sort | tail -n 1)"
if [[ -z "$JAR_FILE" ]]; then
  echo "No application JAR found in $TARGET_DIR" >&2
  exit 1
fi

# Runtime deps are already in target/release-lib (copied by the release Maven profile)
RELEASE_LIB_SRC="$TARGET_DIR/release-lib"
if [[ ! -d "$RELEASE_LIB_SRC" ]]; then
  echo "target/release-lib not found – make sure the 'release' Maven profile ran correctly." >&2
  exit 1
fi

log "Preparing release folder: $RELEASE_ROOT"
rm -rf "$RELEASE_ROOT"
mkdir -p "$LIB_DIR" "$BIN_DIR"
cp "$JAR_FILE" "$APP_DIR/mdir.jar"
cp "$RELEASE_LIB_SRC/"* "$LIB_DIR/"

cat > "$BIN_DIR/run.bat" <<'EOF'
@echo off
REM MDir Image ^& Video Organizer - Windows Launcher
setlocal
set "SCRIPT_DIR=%~dp0"
set "APP_DIR=%SCRIPT_DIR%..\app"
if not exist "%APP_DIR%\mdir.jar" (
    echo Error: mdir.jar not found at "%APP_DIR%\mdir.jar"
    pause
    exit /b 1
)
echo Launching MDir Image ^& Video Organizer...
java --enable-native-access=ALL-UNNAMED -cp "%APP_DIR%\mdir.jar;%APP_DIR%\lib\*" com.girbola.Launcher
if errorlevel 1 (
    echo.
    echo Error: Failed to start the application.
    echo Check console output above for details.
    pause
    exit /b 1
)
endlocal
EOF

cat > "$BIN_DIR/run.sh" <<'EOF'
#!/usr/bin/env bash
# MDir Image & Video Organizer - macOS/Linux Launcher
set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APP_DIR="$(cd "$SCRIPT_DIR/../app" && pwd)"
if [ ! -f "$APP_DIR/mdir.jar" ]; then
  echo "Error: mdir.jar not found at $APP_DIR/mdir.jar"
  exit 1
fi
echo "Launching MDir Image & Video Organizer..."
java --enable-native-access=ALL-UNNAMED -cp "$APP_DIR/mdir.jar:$APP_DIR/lib/*" com.girbola.Launcher
EOF
chmod +x "$BIN_DIR/run.sh"

cat > "$RELEASE_ROOT/README.md" <<EOF
# MDir v${RELEASE_VERSION} Release

This folder was generated by scripts/build-release.sh.

## Run

- Windows: bin/run.bat
- macOS/Linux: chmod +x bin/run.sh && ./bin/run.sh

## Requirements

- Java 24+
- Extract the ZIP before running
EOF

if command -v zip >/dev/null 2>&1; then
  log "Creating ZIP archive"
  rm -f "$ZIP_PATH"
  (cd "$RELEASE_ROOT/.." && zip -qr "$ZIP_PATH" "$RELEASE_NAME")
  log "ZIP created: $ZIP_PATH"
else
  log "zip command not found; skipping archive creation"
fi

log "Release folder ready: $RELEASE_ROOT"

